import type { Metadata } from "next";
import * as Font from "@/utils/font";
import "./globals.css";


export const metadata: Metadata = {
  title: "Hashim541",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Font.sourcecode.className} `}>{children}</body>
    </html>
  );
}
